[CmdletBinding()]
param(
    # An opaque, owner-local staging copy. This is never an original source
    # directory and must contain the marker created by the verified sampler.
    [Parameter(Mandatory = $true)]
    [string]$StagingPath,

    # Limited to the four ignored owner-only env files generated by this
    # script. Useful only before a full runtime contains business data.
    [switch]$RotateGeneratedEnvironment
)

# Creates the ignored owner-only endpoint configuration for the full private
# library. Runtime media lives in Docker-managed POSIX volumes; the only host
# bind it permits is a pre-verified opaque staging directory mounted read-only
# into Piwigo for import. It never accepts an original-source path.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$privateDirectory = Join-Path $projectRoot 'infra\private-full'
$privateWorkRoot = Join-Path $projectRoot '.codex-work\private-real-full'
$wsl = "$env:SystemRoot\System32\wsl.exe"
$script:stage = 'initialization'

. (Join-Path $PSScriptRoot 'secret-file-acl.ps1')

function Set-ClassArchiveOwnerOnlyDirectoryAcl([string]$Path) {
    $resolved = (Resolve-Path -LiteralPath $Path -ErrorAction Stop).Path
    $item = Get-Item -LiteralPath $resolved -Force -ErrorAction Stop
    if (-not $item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw 'private_directory_path_untrusted'
    }
    try {
        Assert-ClassArchiveOwnerOnlyFileAcl -Path $resolved
        return
    }
    catch { }
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent().User
    if ($null -eq $identity) { throw 'private_acl_identity_unavailable' }
    $systemSid = [Security.Principal.SecurityIdentifier]::new('S-1-5-18')
    $administratorsSid = [Security.Principal.SecurityIdentifier]::new('S-1-5-32-544')
    $acl = [Security.AccessControl.DirectorySecurity]::new()
    $acl.SetOwner($identity)
    $acl.SetAccessRuleProtection($true, $false)
    $inheritance = [Security.AccessControl.InheritanceFlags]::ContainerInherit -bor [Security.AccessControl.InheritanceFlags]::ObjectInherit
    foreach ($sid in @($identity, $systemSid, $administratorsSid)) {
        [void]$acl.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new(
            $sid, [Security.AccessControl.FileSystemRights]::FullControl, $inheritance,
            [Security.AccessControl.PropagationFlags]::None, [Security.AccessControl.AccessControlType]::Allow
        ))
    }
    Set-Acl -LiteralPath $resolved -AclObject $acl
    Assert-ClassArchiveOwnerOnlyFileAcl -Path $resolved
}

function Stop-Prepare([string]$Code) {
    throw [InvalidOperationException]::new('PRIVATE_FULL_ENV_STOP:' + $Code)
}

function New-SecretText {
    $bytes = New-Object byte[] 48
    $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
    return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

function Convert-ToWslPath([string]$Path) {
    $result = @(& $wsl -d Ubuntu --exec wslpath -a $Path 2>&1)
    if ($LASTEXITCODE -ne 0 -or $result.Count -ne 1 -or [string]$result[0] -notmatch '^/mnt/[a-z]/') {
        Stop-Prepare 'wsl_path_failed'
    }
    return [string]$result[0]
}

function Assert-IgnoredTarget([string]$Path) {
    $relative = $Path.Substring($projectRoot.TrimEnd('\').Length + 1).Replace('\', '/')
    & git -C $projectRoot check-ignore --quiet --no-index -- $relative
    if ($LASTEXITCODE -ne 0) { Stop-Prepare 'target_not_ignored' }
}

function Write-PrivateFile([string]$Path, [string[]]$Lines) {
    if (Test-Path -LiteralPath $Path) { Stop-Prepare 'target_already_exists' }
    Assert-IgnoredTarget $Path
    $temporary = $Path + '.partial-' + [Guid]::NewGuid().ToString('N')
    try {
        [IO.File]::WriteAllText($temporary, ([string]::Join("`n", $Lines) + "`n"), [Text.UTF8Encoding]::new($false))
        Set-ClassArchiveOwnerOnlyFileAcl -Path $temporary
        Move-Item -LiteralPath $temporary -Destination $Path -ErrorAction Stop
        Assert-ClassArchiveOwnerOnlyFileAcl -Path $Path
    }
    finally {
        if (Test-Path -LiteralPath $temporary -PathType Leaf) {
            Remove-Item -LiteralPath $temporary -Force -ErrorAction SilentlyContinue
        }
    }
}

function Remove-GeneratedPrivateFile([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return }
    Assert-IgnoredTarget $Path
    Assert-ClassArchiveOwnerOnlyFileAcl -Path $Path
    Remove-Item -LiteralPath $Path -Force -ErrorAction Stop
    if (Test-Path -LiteralPath $Path) { Stop-Prepare 'generated_env_rotation_failed' }
}

function Ensure-IgnoredPrivateDirectory([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path)) {
        [void](New-Item -ItemType Directory -Path $Path -Force -ErrorAction Stop)
    }
    $item = Get-Item -LiteralPath $Path -Force -ErrorAction Stop
    if (-not $item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) { Stop-Prepare 'private_work_path_untrusted' }
    $relative = $item.FullName.Substring($projectRoot.TrimEnd('\').Length + 1).Replace('\', '/')
    & git -C $projectRoot check-ignore --quiet --no-index -- $relative
    if ($LASTEXITCODE -ne 0) { Stop-Prepare 'private_work_path_not_ignored' }
    Set-ClassArchiveOwnerOnlyDirectoryAcl -Path $item.FullName
    return $item.FullName
}

function Assert-OpaqueStaging([string]$Path) {
    $full = [IO.Path]::GetFullPath($Path)
    $item = Get-Item -LiteralPath $full -Force -ErrorAction Stop
    if (-not $item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) { Stop-Prepare 'opaque_staging_untrusted' }
    # A source root cannot satisfy this opaque ingress contract: it must carry
    # the exact, path-free sampler marker plus hashed staging basenames only.
    $marker = Join-Path $full '.classarchive-private-full-staging-v1.json'
    if (-not (Test-Path -LiteralPath $marker -PathType Leaf)) { Stop-Prepare 'opaque_staging_marker_missing' }
    try { $record = Get-Content -LiteralPath $marker -Raw -Encoding UTF8 | ConvertFrom-Json -ErrorAction Stop } catch { Stop-Prepare 'opaque_staging_marker_invalid' }
    if ([string]$record.version -ne '1' -or [string]$record.layout -ne 'OPAQUE_HASHED_FILES' -or [string]$record.import_digest -notmatch '^[a-f0-9]{64}$') {
        Stop-Prepare 'opaque_staging_marker_invalid'
    }
    $names = @(Get-ChildItem -LiteralPath $full -File -Force | Where-Object { $_.Name -ne '.classarchive-private-full-staging-v1.json' } | Select-Object -ExpandProperty Name)
    if ($names.Count -lt 1 -or @($names | Where-Object { $_ -notmatch '^frl-[a-f0-9]{64}\.(jpg|jpeg|png|webp)$' }).Count -ne 0) {
        Stop-Prepare 'opaque_staging_layout_invalid'
    }
    return @{ path = $full; import_digest = [string]$record.import_digest; wsl = (Convert-ToWslPath $full) }
}

try {
    $script:stage = 'opaque_staging'
    $staging = Assert-OpaqueStaging $StagingPath
    $script:stage = 'private_directories'
    $manifestDirectory = Ensure-IgnoredPrivateDirectory (Join-Path $privateWorkRoot 'manifests')
    $runtimeDirectory = Ensure-IgnoredPrivateDirectory (Join-Path $privateWorkRoot 'runtime')
    $extensionCacheDirectory = Ensure-IgnoredPrivateDirectory (Join-Path $runtimeDirectory 'official-extension-cache')
    $manifestPath = Join-Path $manifestDirectory 'full-real-import-manifest.json'
    if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) { Stop-Prepare 'import_manifest_missing' }
    Assert-ClassArchiveOwnerOnlyFileAcl -Path $manifestPath
    $manifestWsl = Convert-ToWslPath $manifestPath
    $cacheWsl = Convert-ToWslPath $extensionCacheDirectory
    if ($manifestWsl -notmatch '^/mnt/c/' -or $cacheWsl -notmatch '^/mnt/c/') { Stop-Prepare 'private_runtime_path_invalid' }

    $script:stage = 'target_files'
    $targets = @(
        (Join-Path $privateDirectory '.env.piwigo.staging'),
        (Join-Path $privateDirectory '.env.immich.staging'),
        (Join-Path $privateDirectory '.env.piwigo.owner'),
        (Join-Path $privateDirectory '.env.immich.owner')
    )
    foreach ($target in $targets) {
        if (Test-Path -LiteralPath $target) {
            if (-not $RotateGeneratedEnvironment) { Stop-Prepare 'target_already_exists' }
            Remove-GeneratedPrivateFile $target
        }
        Assert-IgnoredTarget $target
    }

    $script:stage = 'secrets'
    $piwigoDb = New-SecretText
    $piwigoRoot = New-SecretText
    $claimPepper = New-SecretText
    $pseudonymSecret = New-SecretText
    $immichDb = New-SecretText
    $storageMode = 'DOCKER_MANAGED_POSIX_VOLUMES'

    $commonPiwigo = @(
        'COMPOSE_PROJECT_NAME=class_archive_private_full_v3_piwigo',
        'CLASS_ARCHIVE_GATEWAY_NETWORK=class_archive_private_full_v3_gateway',
        'CLASS_ARCHIVE_TIMEZONE=Asia/Shanghai',
        ('PRIVATE_FULL_MANAGED_STORAGE_MODE=' + $storageMode),
        ('FULL_REAL_STAGING_PATH=' + $staging.wsl),
        ('FULL_REAL_IMPORT_MANIFEST_PATH=' + $manifestWsl),
        ('PRIVATE_FULL_EXTENSION_CACHE_PATH=' + $cacheWsl),
        'PIWIGO_UID=1000', 'PIWIGO_GID=1000',
        'PIWIGO_DATA_VOLUME=class_archive_private_full_v3_control_piwigo_data',
        'PIWIGO_UPLOADS_VOLUME=class_archive_private_full_v3_piwigo_uploads',
        'PIWIGO_GALLERIES_VOLUME=class_archive_private_full_v3_piwigo_galleries',
        'PIWIGO_DERIVATIVES_VOLUME=class_archive_private_full_v3_piwigo_derivatives',
        'PIWIGO_DB_VOLUME=class_archive_private_full_v3_control_piwigo_db',
        'PIWIGO_SCRIPTS_VOLUME=class_archive_private_full_v3_control_piwigo_scripts',
        'PIWIGO_BACKUPS_VOLUME=class_archive_private_full_v3_piwigo_backups',
        'PIWIGO_IMAGE=piwigo/piwigo:16.4.0a@sha256:0ec6f159a3f972338b64e299d56ac37c442dd26cbeec39320d76ea826b5e0b84',
        'MARIADB_IMAGE=mariadb:11.8.8@sha256:d9f7eb2637296652f24b484afd5d246f759f49f5babcadc6a9e344c9acb75fbf',
        'DB_NAME=piwigo', 'DB_USER=piwigo',
        ('DB_PASSWORD=' + $piwigoDb), ('DB_ROOT_PASSWORD=' + $piwigoRoot),
        'PIWIGO_ADMIN_USERNAME=private-full-admin',
        'PIWIGO_ADMIN_EMAIL=admin@private-full.invalid',
        ('CLASS_ARCHIVE_CLAIM_CODE_PEPPER=' + $claimPepper),
        ('CLASS_ARCHIVE_ANONYMOUS_PSEUDONYM_SECRET=' + $pseudonymSecret),
        'SMTP_HOST=', 'SMTP_PORT=', 'SMTP_USERNAME=', 'SMTP_PASSWORD=', 'SMTP_ENCRYPTION='
    )
    $commonImmich = @(
        'IMMICH_COMPOSE_PROJECT_NAME=class_archive_private_full_v3_immich',
        'CLASS_ARCHIVE_GATEWAY_NETWORK=class_archive_private_full_v3_gateway',
        ('PRIVATE_FULL_MANAGED_STORAGE_MODE=' + $storageMode),
        'IMMICH_UPLOAD_VOLUME=class_archive_private_full_v3_immich_upload',
        'IMMICH_MODEL_CACHE_VOLUME=class_archive_private_full_v3_immich_model_cache',
        'IMMICH_DB_VOLUME=class_archive_private_full_v3_control_immich_db',
        'IMMICH_GATEWAY_SECRET_VOLUME=class_archive_private_full_v3_control_immich_gateway_secret',
        'PIWIGO_UPLOADS_VOLUME=class_archive_private_full_v3_piwigo_uploads',
        'PIWIGO_GALLERIES_VOLUME=class_archive_private_full_v3_piwigo_galleries',
        ('DB_PASSWORD=' + $immichDb), 'DB_USERNAME=postgres', 'DB_DATABASE_NAME=immich', 'TZ=Asia/Shanghai'
    )

    $script:stage = 'write_env'
    Write-PrivateFile (Join-Path $privateDirectory '.env.piwigo.staging') (@(
        'CLASS_ARCHIVE_HTTP_PORT=8290', 'CLASS_ARCHIVE_COMPAT_HTTP_PORT=8291', 'CLASS_ARCHIVE_BASE_URL=http://127.0.0.1:8290'
    ) + $commonPiwigo)
    Write-PrivateFile (Join-Path $privateDirectory '.env.immich.staging') (@(
        'CLASS_ARCHIVE_COMPAT_HTTP_PORT=8291', 'CLASS_ARCHIVE_CORE_PUBLIC_PORT=8290'
    ) + $commonImmich)
    Write-PrivateFile (Join-Path $privateDirectory '.env.piwigo.owner') (@(
        'CLASS_ARCHIVE_HTTP_PORT=8190', 'CLASS_ARCHIVE_COMPAT_HTTP_PORT=8191', 'CLASS_ARCHIVE_BASE_URL=http://127.0.0.1:8190'
    ) + $commonPiwigo)
    Write-PrivateFile (Join-Path $privateDirectory '.env.immich.owner') (@(
        'CLASS_ARCHIVE_COMPAT_HTTP_PORT=8191', 'CLASS_ARCHIVE_CORE_PUBLIC_PORT=8190'
    ) + $commonImmich)

    Write-Output ('PRIVATE_FULL_ENV=PASS files=4 storage_mode=' + $storageMode + ' staging=OPAQUE_READ_ONLY secrets=not_logged')
    exit 0
}
catch {
    $failureCode = $null
    if ($_.Exception.Message -match '^PRIVATE_FULL_ENV_STOP:([a-z0-9_]{1,128})$') { $failureCode = [string]$Matches[1] }
    if ($null -ne $failureCode) {
        Write-Output "PRIVATE_FULL_ENV=FAIL code=$failureCode"
        exit 2
    }
    $name = $_.Exception.GetType().Name
    if ($name -notmatch '^[A-Za-z0-9]{1,64}$') { $name = 'Exception' }
    Write-Output ('PRIVATE_FULL_ENV=FAIL code=unexpected_' + $script:stage + '_' + $name)
    exit 2
}
