{include file=$CA_HEADER_TEMPLATE}
<div class="ca-admin__panel"><h3>班级档案</h3><p class="ca-admin__muted">档案日期与上传时间分开保存。请根据记忆填写可信范围，不要把文件上传时间伪装成拍摄时间。原图始终由 Piwigo 管理，多个相册只建立关联，不复制文件。</p>
<div class="ca-admin__panel"><h4>建立正式档案相册</h4><form method="post" class="ca-admin__form"><input type="hidden" name="pwg_token" value="{$CA_PWG_TOKEN|escape:'html'}"><input type="hidden" name="action" value="create_archive_album"><label>归档分区<select name="era"><option value="HERITAGE">班级历史</option><option value="LIVING">毕业后动态</option></select></label><label>相册名称<input type="text" name="album_name" maxlength="190" required></label><label>相册说明<textarea name="album_comment" maxlength="2000"></textarea></label><label>建立理由<input type="text" name="reason" maxlength="500" required></label><button type="submit">建立相册</button></form></div>
<table><thead><tr><th>图片</th><th>档案分区</th><th>档案日期</th><th>来源</th><th>保存信息</th></tr></thead><tbody>
{foreach from=$CA_ARCHIVE_IMAGES item=image}
<tr><td>图片记录 #{$image.image_id|escape:'html'}<br>{$image.file|escape:'html'}<br>{$image.width|escape:'html'} × {$image.height|escape:'html'}</td><td>{$image.era_label|escape:'html'}</td><td>{if $image.archive_date}{$image.archive_date|escape:'html'} · {/if}{$image.precision_label|escape:'html'}<br>{$image.confidence_label|escape:'html'}<br>{$image.event_label|default:'—'|escape:'html'}</td><td>{if $image.submission_id}{$image.roster_code|escape:'html'} · {$image.real_name|escape:'html'}<br>{$image.original_filename|escape:'html'}<br>{$image.submission_state_label|escape:'html'}{else}Piwigo 原有档案{/if}</td><td><form method="post" class="ca-admin__form"><input type="hidden" name="pwg_token" value="{$CA_PWG_TOKEN|escape:'html'}"><input type="hidden" name="action" value="save_archive_metadata"><input type="hidden" name="image_id" value="{$image.image_id|escape:'html'}"><label>分区<select name="era"><option value="HERITAGE"{if $image.era == 'HERITAGE'} selected{/if}>班级历史</option><option value="LIVING"{if $image.era == 'LIVING'} selected{/if}>毕业后动态</option></select></label><label>日期<input type="text" name="archive_date" placeholder="YYYY-MM-DD / YYYY-MM"></label><label>日期范围<select name="date_precision"><option value="UNKNOWN">日期未知</option><option value="EXACT">日期精确</option><option value="DAY">仅确定到日</option><option value="MONTH">仅确定到月份</option><option value="YEAR">仅确定年份</option><option value="TERM">仅确定学期</option><option value="EVENT_ONLY">仅确定事件</option></select></label><label>可信度<select name="date_confidence"><option value="UNKNOWN">未评估</option><option value="HIGH">高可信</option><option value="MEDIUM">中可信</option><option value="LOW">低可信</option></select></label><label>归档相册<select name="album_id"><option value="">对应分区根相册</option>{foreach from=$CA_ARCHIVE_ALBUMS item=album}<option value="{$album.id|escape:'html'}">{$album.name|escape:'html'}</option>{/foreach}</select></label><label>事件标签<input type="text" name="event_label" maxlength="190"></label><label><input type="checkbox" name="official" value="1"{if $image.official} checked{/if}> 正式档案</label><label>变更理由<input required type="text" name="reason" maxlength="500"></label><button type="submit">保存档案信息</button></form></td></tr>
{foreachelse}<tr><td colspan="5">暂无已归档图片</td></tr>{/foreach}
</tbody></table></div>
</section>
