{include file=$CA_HEADER_TEMPLATE}
<div class="ca-admin__panel"><h3>认领码 / 邀请状态</h3><p class="ca-admin__muted">这里只显示生命周期元数据。原始认领码和邀请码不会从数据库重新读取或再次显示。</p>
<table><thead><tr><th>类型</th><th>身份 / 席位</th><th>代次</th><th>签发时间</th><th>过期时间</th><th>状态</th><th>操作</th></tr></thead><tbody>
{foreach from=$CA_INVITATIONS item=invite}<tr><td>{$invite.purpose_label|escape:'html'}</td><td>{if $invite.roster_code}{$invite.roster_code|escape:'html'} · {$invite.real_name|escape:'html'} · {$invite.seat_type_label|escape:'html'}{/if}</td><td>{$invite.generation|escape:'html'}</td><td>{$invite.issued_at|escape:'html'}</td><td>{$invite.expires_at|escape:'html'}</td><td><span class="ca-admin__badge">{$invite.state_label|escape:'html'}</span></td><td>
{if $invite.purpose == 'CLAIM' && ($invite.state == 'ISSUED' || $invite.state == 'RESERVED')}<form method="post" class="ca-admin__inline" data-confirm="撤销后该认领码将立即永久失效，确认继续？"><input type="hidden" name="pwg_token" value="{$CA_PWG_TOKEN|escape:'html'}"><input type="hidden" name="action" value="revoke_claim"><input type="hidden" name="token_id" value="{$invite.id|escape:'html'}"><label>撤销原因<input name="reason" maxlength="500" required></label><button class="ca-admin__danger" type="submit">撤销</button></form>
{elseif $invite.purpose == 'FAMILY_INVITE' && $invite.state == 'ISSUED'}<form method="post" class="ca-admin__inline" data-confirm="撤销后旧邀请码立即永久失效，席位恢复可用。确认继续？"><input type="hidden" name="pwg_token" value="{$CA_PWG_TOKEN|escape:'html'}"><input type="hidden" name="action" value="revoke_family_invitation"><input type="hidden" name="token_id" value="{$invite.id|escape:'html'}"><label>撤销原因<input name="reason" maxlength="500" required></label><button class="ca-admin__danger" type="submit">撤销</button></form>
{elseif $invite.purpose == 'FAMILY_INVITE' && ($invite.state == 'REVOKED' || $invite.state == 'EXPIRED') && ($invite.seat_state == 'AVAILABLE' || $invite.seat_state == 'INVITED')}<form method="post" class="ca-admin__inline" data-confirm="将生成新的单次邀请码，旧邀请码不会恢复。确认继续？"><input type="hidden" name="pwg_token" value="{$CA_PWG_TOKEN|escape:'html'}"><input type="hidden" name="action" value="reissue_family_invitation"><input type="hidden" name="seat_id" value="{$invite.seat_id|escape:'html'}"><label>重新签发原因<input name="reason" maxlength="500" required></label><button type="submit">重新签发</button></form>
{else}—{/if}</td></tr>{foreachelse}<tr><td colspan="7">暂无 Claim 或邀请记录。</td></tr>{/foreach}
</tbody></table></div></section>
